#!/usr/bin/env bash
# Create a dump file from mysql and compress it

USER="root"
PASS="$1"

DATE=$(date +'%d-%m-%Y')

mysqldump -u $USER -p$PASS --all-databases > backup.sql

FILE="$DATE.tar.gz"

tar -czf $FILE -C . backup.sql
