#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# displays To infinity and beyond indefinitely
# displays I hate the kill command when receiving a SIGTERM signal
# displays Y U no love me?! when receiving a SIGINT signal
# deletes the file /var/run/myscript.pid and terminates itself 
# when receiving a SIGQUIT or SIGTERM signal

sigterm_handler() {
	echo "I hate the kill command"
	sudo rm -r /var/run/myscript.pid
	exit 0
}
sigint_handler() {
	echo "Y U no love me?!"
}
sig_quit() {
	sudo rm -r /var/run/myscript.pid
	exit 0
}

trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sig_quit' SIGQUIT
 
sudo touch /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid

while true;
do
	echo "To infinity and beyond";
	sleep 2
done
