#!/usr/bin/env bash
# Stop 4-to_infinity_and_beyond using kill
#pid=$( ps aux | grep "[4]-to_infinity_and_beyond" | grep "S+" | awk '{print $2}' )

pid=$( pgrep 4-to_infinity_and_beyond )
kill "$pid"
