#!/usr/bin/env bash
# FizzBuzz

x=1

while [ $x -lt 101 ];
do
	a=$(( x % 15 ))
	b=$(( x % 5 ))
	c=$(( x % 3 ))
	if [ $a -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $b -eq 0 ]; then
		echo "Buzz"
	elif [ $c -eq 0 ]; then
		echo "Fizz"
	else
		echo "$x"
	fi
	x=$(( x + 1 ))
done
