#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
# displays:
# username
# user id
# Home directory path for the user - using while loop

while IFS=":" read -r username _ userid _ _ home _;
do
	echo "$username"
	echo "$userid"
	echo "$home"
done < /etc/passwd
