#!/usr/bin/env bash
# Displays Best School 10 times, 
# but for the 9th iteration, displays Best School and 
# then Hi on a new line - Using while loop and if statement.

x=0

while [ $x -lt 10 ];
do
	echo "Best School"
	if [ $x -eq 8 ]; then
		echo -e "Hi"
	fi
	x=$(( x + 1 ))
done
