#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59 - using while loop

x=0

while [ $x -lt 13 ];
do
	y=1
	echo "Hour: $x";
	while [ $y -lt 60 ];
	do
		echo "$y";
		y=$(( y + 1 ))
	done
	x=$(( x + 1 ))
done
