#!/usr/bin/env bash
# Configures an Ubuntu server to:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

cp /etc/hosts ~/hosts.new

sed -i 's/^127.0.0.1.*localhost/127.0.0.2 localhost/' ~/hosts.new
sed -i 's/^0.0.0.0.*facebook.com/8.8.8.8 facebook.com/' ~/hosts.new

sudo cp -f ~/hosts.new /etc/hosts
